empresa_empresa_gafetes_mostrar_gafetes:
    path:     /
    defaults: { _controller: EmpresaEmpresaGafetesBundle:EmpresaGafetes:mostrarGafetes }
    methods: GET
#Ver todos los gafetes del vendedor
empresa_empresa_gafetes_mostrar_gafetes_vendedor:
    path:     /vendedor/{idVendedor}
    defaults: { _controller: EmpresaEmpresaGafetesBundle:EmpresaGafetes:mostrarGafetesVendedor, idVendedor:0 }
    methods: GET
    requirements:
        idVendedor: \d+
#Ver los gafetes por empresa
empresa_empresa_gafetes_mostrar_gafetes_empresa:
    path:     /empresa/{idVendedor}/{idEmpresa}
    defaults: { _controller: EmpresaEmpresaGafetesBundle:EmpresaGafetes:mostrarGafetesEmpresa, idVendedor:0, idEmpresa:0 }
    methods: GET
    requirements:
        idVendedor: \d+
        idEmpresa: \d+
#Ver todos los gafetes de las empresas
empresa_empresa_gafetes_mostrar_gafetes_todos:
    path:     /empresa/gafetes
    defaults: { _controller: EmpresaEmpresaGafetesBundle:EmpresaGafetes:mostrarTodosGafetes }
    methods: GET
