# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        LoginBundle\Model\Profile:
            algorithm: sha1
            iterations: 1
            encode_as_base64: false
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id: app.ixposuser_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        tracking:
            pattern: ^/tramarketing
            security: false

        main:
            anonymous: ~
            http_basic: ~
            form_login:
                check_path: /login_check
                login_path: /
                default_target_path: /dashboard
            logout:
                path:   /logout
                target: /
                invalidate_session: true

    access_control:
        - { path: (^/$|^/es$|^/en|^/back_door|^/utilerias|^/api|^/msapi/*), roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/fp/exhibitor|^/lt/exhibitor, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: [ROLE_USER, ROLE_IXPO] }
        # activate different ways to authenticate

        # http_basic: ~
        # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

        # form_login: ~
        # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
